MCP_SERVERS={
    "filesystem":{
        "transport":"stdio",
        "command":"npx",
        "args":[
            "-y",
            "@modelcontextprotocol/server-filesystem",
            "."
        ]
    }
}